### PR TITLE
Update BatteryHealth.json

### PR DESCRIPTION
**Pull request by SiNaPsEr0x**
fix for correct value especially with cold weather

### CODE REVIEW

**Comment by jheredianet** [comment]
Hi, I see you are still just putting just >15. Why not 14, 17, 20 or even directly 30 or something else.  What we need is not a fixed valued. We need a variable value (a calculation formula that give us that value) based on some information logged on charges table.

**Comment by SiNaPsEr0x** [comment]
I chose 15 for the simple reason that I noticed that the battery heats up after about 7, 8 kWh and therefore the ice symbol disappears that’s why I preferred to stay wide with the numbers

**Comment by SiNaPsEr0x** [comment]
Also because this does not involve a problem, as almost everyone at least once a month make a recharge of that size that is not a lot, in this way even if it fishes from less data it fishes them with a higher time order and therefore you can better see the difference in time

**Comment by jheredianet** [comment]
> I chose 15 for the simple reason that I noticed that the battery heats up after about 7, 8 kWh and therefore the ice symbol disappears that’s why I preferred to stay wide with the numbers

This is a good point, but still its not the same charging at home or at a Super charge, it must be up at the power and battery heather.

**Comment by jheredianet** [comment]
> Also because this does not involve a problem, as almost everyone at least once a month make a recharge of that size that is not a lot, in this way even if it fishes from less data it fishes them with a higher time order and therefore you can better see the difference in time, Actually as you could see from my data, my battery corresponds to these values and not to those of before

Let me do a further research and test with other Tesla models to see how it goes.

**Comment by SiNaPsEr0x** [comment]
> > I chose 15 for the simple reason that I noticed that the battery heats up after about 7, 8 kWh and therefore the ice symbol disappears that’s why I preferred to stay wide with the numbers
> 
> 
> 
> This is a good point, but still its not the same charging at home or at a Super charge, it must be up at the power and battery heather. 

On suc you Charge more of 10kwh 🤣

**Comment by jheredianet** [comment]
Hi, could you send a screen shot of what you get with this query?

`SELECT model, efficiency, trim_badging, wheel_type marketing_name FROM cars`

image

I'm refactoring the main queries of this dashboard, and next weekend will have the opportunity to make some tests with other friend cars on road charging in cold weather, in order to see how it goes.

**Comment by SiNaPsEr0x** [comment]
Sorry for the absence I was on vacation in the mountains:
image

**Comment by jheredianet** [comment]
Great, I hope you enjoyed your free days. Thank you for sharing your data. This weekend I'll test. 
These days, I've been doing a complete reengineering of all calculations. You'll have news soon. 

Regards,

**Comment by SiNaPsEr0x** [comment]
I understand that you don't have a Tesla.. I hope one day you can be part of the big family!

**Comment by jheredianet** [comment]
> I understand that you don't have a Tesla.. I hope one day you can be part of the big family!

I do, on like yours from Aug 2020. But we need to have in mind that calculations must be general for any model. This dashboard for me was very accurate until I shared, then realized that it was showing some estrange values in different conditions, that's why I need to be sure that all the changes I'm doing works for every model.

**Comment by SiNaPsEr0x** [comment]
Ah great! The beauty of github is that you share a lot of experiences guided only by passion at times .. perfect I follow you!

**Comment by jheredianet** [comment]
> Ah great! The beauty of github is that you share a lot of experiences guided only by passion at times .. perfect I follow you!
Hi @SiNaPsEr0x, would you mind to send me a PM on Twitter? you have it on my profile. 
I'd like to share with you first the changes I'm doing to see how it goes. Thanks.

**Comment by SiNaPsEr0x** [comment]
@sin4pse on Twitter

**Pull request closed without merging**
