### PR TITLE
Temperature and speed related dashboard

### PR DESCRIPTION
**Pull request by tero-jarvinen**
New dashboard for temperature and speed related metrics.

### CODE REVIEW

**Comment by jheredianet** [comment]
Thank you, I will merge but send it to a feature branch until is prepared for first release

**Comment by sdwalker** [comment]
Has the typical unit issues

**Comment by jheredianet** [comment]
> Has the typical unit issues

Yes, this is just a preliminar dashboard still in development. When it's ready it will be available in the main branch.

**Comment by jheredianet** [comment]
> Hi @jheredianet , Do you have some time to look into the unit issues and ship out this dashboard as a standard one?

Hi, that dashboard is still in development, that's why it's still in the develop branch. Anyway, once I release the version, I'll keep it here as a custom dashboard for a while until people give me their impressions and comments. Once it's used and accepted enough, I'll upload it to the main Teslamate repository as another standard dashboard.

**Pull request merged**
