### PR TITLE
Update BatteryHealth.json

### PR DESCRIPTION
**Pull request by SiNaPsEr0x**
Fix for ice climates with more reliable calculation based on higher charge percentages (15kwh)

### CODE REVIEW

**Comment by jheredianet** [comment]
Hello, thanks for your contribution, but I think that raising the value arbitrarily would not always be appropriate. Changing that value would only set it aside for your car and your data. The question is, what about cars with a bigger or smaller battery? Therefore I consider that this value should be based on the actual size of the battery, getting that information from somewhere based on the model of the car. But Tesla does not provide this data anywhere, it could only be known if an ODB2 scanner is connected to the car.

I am going to do a deeper analysis of the subject to see how to clean the samples by taking data of "good recharges" based on other parameters of data logged in TeslaMate. Any idea is welcome.

**Comment by SiNaPsEr0x** [comment]
50kwh tesla... sr+2020 Ok imagine but with small refills incorrect values come out especially if the battery is still frozen ...

**Comment by SiNaPsEr0x** [comment]
The value would only take into account the recharges greater than 15kwh and not 5... this is because in all that time the battery has heated up and the data written in the end will be correct, not only my car is taken with those values 😅 have you never loaded 15kwh?

**Comment by jheredianet** [comment]
> The value would only take into account the recharges greater than 15kwh and not 5... this is because in all that time the battery has heated up and the data written in the end will be correct, not only my car is taken with those values 😅 have you never loaded 15kwh?

Yes, of course, that value must be increased to clean the samples. The question is knowing what value to consider. 15kWh for a 50kWh battery might be fine, but not for a larger battery. The thing here would be to consider charges of 3/4 of the battery or so, but sin don't know that value for sure, that's why I'm trying to estimated it.  As I said before, I'm going to do a deeper analysis of the subject to see how to clean the samples by taking data of "good recharges" based on other parameters of data logged in TeslaMate.

In the mean time if you consider that 15kWh is good enough for you, you could set that value in your own.

**Comment by SiNaPsEr0x** [comment]
>= Excuse me man ... because what problem would you give to those who charge the most?

**Comment by jheredianet** [comment]
Not a problem, It's just a thing about accurate estimation. I'll need to test with other model cars. Happily I've have friends in city who can help me testing. As soon as I have time to investigate and test, you will have news.

**Comment by SiNaPsEr0x** [comment]
It’s always a pleasure to help improve things ☺️

**Comment by SiNaPsEr0x** [comment]
for your preview.... FROM THIS:

image


to this:

image



It is much more accurate like this ..

**Comment by jheredianet** [comment]
Yeah, it seems more accurate. Great!

**Comment by SiNaPsEr0x** [comment]
this is the file correct ... I remove the branch... if you need I push the new mod fixed

**Comment by jheredianet** [comment]
Sure, but could you please push it to the developer branch?, so I can test it first and make other adjustments I have in mind. Thanks.

**Pull request closed without merging**
