### PR TITLE
Update CurrentState.json

### PR DESCRIPTION
**Pull request by hectorrf16**
Fixing Pie Chart Colors to match with the ones in the Timeline

### CODE REVIEW

**Comment by jheredianet** [comment]
Great catch. Thanks!

**Comment by sdwalker** [comment]
image

Is there any way to match the font colors from the timeline so the pie chart isn't all light text?

**Comment by jheredianet** [comment]
I’m not sure if it’s possible with a Pie Chart in Grafana. I’ll try to dig further

**Comment by hectorrf16** [comment]
It can be changed. Just click on the color next to the legend text.

**Comment by jheredianet** [comment]
That’s what we already did in this merge. In this case we see taking about changing the font color.

**Comment by hectorrf16** [comment]
image

Sorry @sdwalker as @jheredianet said, grafana doesn't allow to change the text color.. i thought this was possible, but not... :(

**Pull request merged**
